# Generated by Django 5.1.3 on 2025-01-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='productview',
            old_name='user',
            new_name='members',
        ),
    ]
